# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
install:
  - Rscript -e "renv::restore()"
script:
  - R CMD build .
  - R CMD check HackerTracker_*.tar.gz
  
deploy:
  skip_cleanup: true
  provider: script
  script:
  - Rscript -e 'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPP_NAME"), secret=Sys.getenv("SHINYAPP_SECRET"), token=Sys.getenv("SHINYAPP_TOKEN"))'
  - Rscript -e 'rsconnect::deployApp(appName="hackertracker", appFiles = grep(list.files(path=".", recursive = TRUE, all.files = T), pattern="renv|rsconnect|.Rproj|.Rprofile|.git|manifest.json"", inv=T, value=T))'
  on:
    branch: feature/heroku_deployment
